# Site settings
title: "Maxwell Mandina"
description: "Sailor Turned Software Engineer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Maxwell Mandina"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "maxwell.mandina@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "7326855813"
#resume_contact_address:         "167 Jackson Ave, Brooklyn"

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a Software Engineer focusing on full-stack Javascript/TypeScript development from the NYC area. I hold a bachelor's degree in Economics and a master's degree in International Transportation Management. I started learning computer science at Rutgers University, but took a break while I was sailing deep sea as a US Merchant Marine Deck Officer.</p><p>I sailed around the world on all kinds of deep-sea sailing vessels, from tiny tugboats to hulking hospital ships! I started self-teaching software engineering after my shifts onboard every night, and eventually came home to NYC to join the great tech community here.</p></p>I enjoy surfing and traveling, which led me to build my first full stack web application, findSurf (findsurf.maxwellmandina.com). It's the surf atlas I wish existed when I was traveling all over the world, surfing wherever I could find a wave! I'm currently looking for software-engineering roles. If you would like to talk, contact me at maxwell.mandina@gmail.com.</p><p>Fair winds and following seas!</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/mmandina"
  #resume_twitter_url:           ""
  #resume_dribbble_url:          ""
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/maxwell-mandina/"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           ""
 # resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
